services:
  - type: web
    name: python-portfolio
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn python_portfolio.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
    staticPublishPath: staticfiles
